apiVersion: v1
kind: Pod
metadata:
  name: az-devops-agent
spec:
  containers:
    - name: azdevopsagent
      image: multiservicecr.azurecr.io/azdevopsagent:latest
      resources:
        limits:
          memory: 3Gi
        requests:
          memory: 1Gi
      env:
        - name: AZP_URL
          valueFrom:
            secretKeyRef:
              name: azdevops
              key: AZP_URL
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azdevops
              key: AZP_TOKEN
        - name: AZP_POOL
          valueFrom:
            secretKeyRef:
              name: azdevops
              key: AZP_POOL
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: azdevopsagent-volume
  imagePullSecrets:
    - name: azcr-secret
  volumes:
    - name: azdevopsagent-volume
      hostPath:
        path: /var/run/docker.sock
