apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: https://<VmIp>:6443
    name: <cluster-name>
contexts:
  - context:
      cluster: <cluster-name>
      namespace: default
      user: admin
    name: <context-name>
current-context: <context-name>
kind: Config
preferences: {}
users:
  - name: admin
    user:
      password: <password>
      username: admin
